### ISSUE TITLE
As a user I want to be able to flag a task without having to add text in second box.

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.Mobile#100]
Remove mandatory requirement for second text box.  This should be optional until we alter it to corrective actions.  In most cases I expect the info to be added in first box but it is nice to give them extra space to type, should just not be required.

**Comment by j0nscalet** [comment]
@danielqualitykitchen updated the title of this to '..flag a task' since that's what the user is doing.

**Comment by j0nscalet** [comment]
@mgpaja8 This is the one I want you to tackle this week. (Made a mistake commenting on #110 so ignore that). It'll be a stretch since you're getting your laptop on Tuesday and won't have me there to help. I think you can do it though, even if you just get the code into a PR for me to review that's perfect.
