### ISSUE TITLE
As an employee I'd like to see a graphic when no incidents exists so I can feel good

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#29]

**Comment by j0nscalet** [comment]
@ershovd This will make a lot of sense once I have to the new version of the app checked in. It should be fairly easy to do once that's done.

**Comment by ershovd** [comment]
@j0nscalet can you provide concrete details on what you would like me to do on this task? What kind of graphic should be seen by user?

**Comment by j0nscalet** [comment]
@ershovd You can just use a ImageView with an existing image from the Asset Catalog for now. We'll figure out details on the graphic later. 

The way I would approach this is to use a `ContentView` with `HorizontalOptions` and  `VerticalOptions`set to `FillAndExpand`with an ImageView inside. You may have to wrap the root `StackLayout' in an `RelativeLayout` to deal with this. That way the "EmptyView" covers the rest of the page.

That's my two cents, which isn't worth much these days, what do you think?

**Comment by ershovd** [comment]
@j0nscalet I think you approach is good and pretty straigth. I will do the following:
- add an `ImageView` to `IncidentCenterPage.xaml`
- create a bindable property in `IncidentCenterViewModel`  that will map count of Incidents
- set ImageView visible if Count==0 , false otherwise. Maybe the opposite logic needed to be applied for incidentsListView, will see.

My estimate on this task is 2h30m
