### ISSUE TITLE
As a manager I should be able to resolve an incident

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#38]
**Problem**
As a manager I should be able to resolve an incident. This functionality is available in the API but is not available in the app.

**Questions**
- Does a manager need to be able to re-open an incident? Say if it was marked as fixed but is not fixed? 
    - If we don't give them the re-open function, what else can a manager do with a fixed incident other than resolve it? Does it make sense for them to continue discussing an incident that's already fixed? 

-  Like the employee in #37, a manager can comment on an incident without resolving it, but a comment is required to resolve it. That being said, how can we incorporate comment+resolve function? Not a lot of screen space here:
![image](https://cloud.githubusercontent.com/assets/1328795/24127337/025668f8-0d91-11e7-907e-1e0fab47c99a.png)

**Solution**
[Describe potential solutions to the issue. For Design issues you should be writing code in this section]

**Comment by ershovd** [comment]
@j0nscalet  My approach to this issue will be simialiar to #37 e.g:
1. Create xaml for buttons
2. create command for resolving the task
3. wire up command and buttons, make sure the enabling of buttons works properly
4. make sure that buttons display correctly for regular employee and a manager. 

Questions:
- how to detect if employee is a manager? 
- which buttons should be visible to manager? apparently, only manager should be able to see `Resolve` incident buttons?
Initial time for this task is 2h30 (due to questions and potential future complexity involved). I will start with more concrete and clear parts (creating UI)

**Comment by ershovd** [comment]
@j0nscalet  why `QualityKitchen.Mobile.Domain.Model.Employee` doesn't have a `Role` property? compare this to the same class in API https://github.com/j0nscalet/QualityKitchen.API/blob/dev/src/QualityKitchen.Domain/Model/Operation/Employee.cs#L65
