### ISSUE TITLE
Should we unit test our ViewModels?

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#41]
- Is there any value to doing it?

- Should we do automated UI testing instead?

**Comment by j0nscalet** [comment]
@jjvainav What are your thoughts on this?

**Comment by jjvainav** [comment]
UI testing is usually expensive and brittle since the UI often changes. Unless you have some complex UI workflows, I would say it isn't even worth considering.

As for your ViewModels, this would also depend on the complexity of the VM. If your VM doesn't really have logic and is simply a proxy that just exposes properties/logic which exist in, say, the model, it might not be worth creating tests for the VM because test against the model would lready cover you.
