### ISSUE TITLE
Comment placeholder should be reset after comment

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.Mobile#64]
**Problem**
After taking action on the Incident Resolution screen, either by making a comment or a comment+fix the comment textbox placeholder is not reset properly.

Notice how the comment box placeholder is empty in this screenshot:
![image](https://cloud.githubusercontent.com/assets/1328795/25016402/a8bffe06-2034-11e7-872e-db72364390dd.png)

**Questions**
- Placeholder is implemented in ExtendedEditor/ExtendedEditorRenderer using the `ShouldBeginEditing` and `ShouldEndEditing`. 
- Clearing the comment on line 115 and 131 doesn't reset the placeholder as it should

**Solution**
- We may want to look at some different implementations of a placeholder for the Editor view

**Comment by j0nscalet** [comment]
@ershovd Interested on your thoughts on how to approach a solution for this. I think we should focus our attention on `ExtendedEditor` control. Since placeholder functionality is missing from the `Editor` control in XForms the point of the extension was to add it.

I wonder if someone in the community has resolved this issue already?

**Comment by ershovd** [comment]
@j0nscalet I need maybe 30m-45m or something to investigate this issue. The trivial approach will be to send EndEditiing event to control (when clicking button). More proper way is probably to extend the editor properly to fix the issue altogether

**Comment by j0nscalet** [comment]
@ershovd Ok no problem. I agree I think we need to extend the editor properly. The way that I would think about it to make things easier is to think about it like a spike. Essentially we need to create a multiline text field control with placeholder support. 

Probably best to see if others how others have resolved this. When I dug into a few months back I concluded that we needed to `OnTextChanging` event as it seems that `ShouldBeginEdit` and `ShouldEndEdit` doesn't act the way you would think.

**Comment by ershovd** [comment]
@j0nscalet I've tested around a bit, and looks for solution but still no luck (find the similiar to yours implementation https://forums.xamarin.com/discussion/comment/163532/#Comment_163532 ) The whole comment/buttons/placeholder functionality is a little buggy - I've just found a bug - that you can make a comment with empty comment - it specifies "Make Comment..." text, and then the styles become broken. 
Anyway, in terms of this specific issue: the problem is that in `ShouldEndEditing` the `textView.Text` keeps the comment text (the Comment text resets after the text is  event is fired).
One hack which can be done - is to have a special property on ExtendedEditor and set it to true only when you   need to keep the the text (otherwise, always clear it and set to placeholder text).
